services:
  - type: web
    name: tpv-predictions
    runtime: python
    rootDir: tpv-agent
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    plan: free
    autoDeploy: true
